# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "blowfish"

baseURL = "https://danialjfz.github.io/myblog/"
title = "Danial Jafarzadeh | Neural Odyssey"
defaultContentLanguage = "en"
enableRobotsTXT = true
summaryLength = 40
enableGitInfo = true

buildDrafts = false
buildFuture = false

enableEmoji = true

# googleAnalytics = "G-XXXXXXXXX"

[pagination]
  pagerSize = 100

[imaging]
  anchor = 'Center'
  quality = 85
  resampleFilter = 'Lanczos'

[minify]
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepWhitespace = false
    [minify.tdewolff.css]
      keepCSS2 = true
      precision = 1
    [minify.tdewolff.js]
      keepVarNames = false
      precision = 1

[caches]
  [caches.getjson]
    dir = ':cacheDir/:project'
    maxAge = '24h'
  [caches.getcsv]
    dir = ':cacheDir/:project'
    maxAge = '24h'
  [caches.getresource]
    dir = ':cacheDir/:project'
    maxAge = '24h'
  [caches.images]
    dir = ':resourceDir/_gen'
    maxAge = -1
  [caches.assets]
    dir = ':resourceDir/_gen'
    maxAge = -1

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = -1

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "series"
        weight = 50

    [[related.indices]]
        name = "authors"
        weight = 20

    [[related.indices]]
        name = "date"
        weight = 10

    [[related.indices]]
      applyFilter = false
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 10
